// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5qiKPxpAtbaKIZA4B0tiPwP-1j32zgRU',
    appId: '1:176945200162:web:6506540fa8e17b15bd9e7b',
    messagingSenderId: '176945200162',
    projectId: 'auth-13165',
    authDomain: 'auth-13165.firebaseapp.com',
    storageBucket: 'auth-13165.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl0OaNKf3nBCgPplEdPnGCIBBwPTCTvag',
    appId: '1:176945200162:android:cfcdd1f16143aa71bd9e7b',
    messagingSenderId: '176945200162',
    projectId: 'auth-13165',
    storageBucket: 'auth-13165.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwrxzesjXi2IVFiZQEdYYye58hnrknadg',
    appId: '1:176945200162:ios:699e7dca8dde38a7bd9e7b',
    messagingSenderId: '176945200162',
    projectId: 'auth-13165',
    storageBucket: 'auth-13165.appspot.com',
    iosBundleId: 'com.example.register',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwrxzesjXi2IVFiZQEdYYye58hnrknadg',
    appId: '1:176945200162:ios:3de38db1b9352800bd9e7b',
    messagingSenderId: '176945200162',
    projectId: 'auth-13165',
    storageBucket: 'auth-13165.appspot.com',
    iosBundleId: 'com.example.register.RunnerTests',
  );
}
